[workspace]
resolver="3"
members=[ "examples/format-items",
    "examples/greeter"
, "examples/string-formatter"]

[workspace.dependencies]
anyhow = "1.0.98"
cgp = "0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
